frameworkVersion: '2'

service: size-standards-sls
enableLocalInstallationFallback: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'mint'} # Set the default stage used. Default is mint
  region: ${opt:region, 'us-east-1'}
  vpc:
    subnetIds: ${ssm:/${self:provider.stage}/network/private_subnet_ids}
    #securityGroupIds: []
  apiGateway:
    restApiId: ${ssm:/${self:provider.stage}/size_standards/apigw_id}
    restApiRootResourceId: ${ssm:/${self:provider.stage}/size_standards/apigw_root_resource_id}
  role: ${ssm:/${self:provider.stage}/size_standards/lambda_role_arn}

package:
  artifact: workspace/size-standards.zip
  excludeDevDependencies: false

functions:
  question:
    name: ${self:provider.stage}-size-standards-question
    handler: question.handler
    events:
      - http: "GET /isSmallBusiness"
  rest:
    name: ${self:provider.stage}-size-standards-rest
    handler: rest.handler
    events:
      - http: "GET /naics"
      - http: "GET /naics/{proxy+}"
custom:
  config:
    mint:
      account_type: lower
    demo:
      account_type: lower
    venus:
      account_type: lower
    staging:
      account_type: upper
    production:
      account_type: upper
  env: ${self:custom.config.${self:provider.stage}}
